services:
  - type: web
    name: laravel-app
    env: docker
    region: oregon
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    buildFilter:
      paths: ["Dockerfile", "render.yaml", "**/*.php", "composer.*"]
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://laravel-app.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: tu-host-de-db
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: nombre-db
      - key: DB_USERNAME
        value: usuario-db
      - key: DB_PASSWORD
        value: clave-db
